### ISSUE TITLE
Sort stake pools on `desirability`

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1276]
# Context

WB-48

We implemented a module for calculating the `desirability` of stake pools.

WB-48 asks us to order stake pools by `desirability`. This is a step in the direction on ordering by non-myopic pool member rewards as specified by the delegation design spec.

# Decision

Sort the `listStakePools` endpoint on `desirability` instead of performance.

# Acceptance Criteria

- [x] stake-pools (returned from API) _must_ be sorted by desirability.

---

# Development

- We need to specify `R`, the total rewards, somehow  ==> #1288 
- Should be just a couple lines of code to calculate `desirability` and sort using `Cardano.Pool.Ranking`. ==> #1289 
- Not sure how to test. Maybe nothing. Maybe a simple hard-coded integration test. I don't think duplicating the setup for the desirability-calculation in a test would be preferable.

- [x] Revised calculation of the apparent performance ==> #1280 

- [x] Log constants used to calculate `desirability` (as NOTICE when they look oddly small) ==> #1298 
- [x] Small fixup to integration tests ==> #1299

# QA 

- Pools are now ordered by desirability. The desirability-calculation rely on information derived from reward parameters in `block0`. The wallet will exit if the information somehow would not be there.
- Existing integration integration tests verify that the `desirability` ordering the same as the previous `performance`-ordering. (of course, in general they are not the same)
- Golden tests comparing parts of the reward-calculation to the jormungandr docs https://github.com/input-output-hk/cardano-wallet/blob/a0c66af028316d999be49e2e5055fec2fd8e01db/lib/jormungandr/test/unit/Cardano/Wallet/Jormungandr/RewardsSpec.hs#L74.
- `totalRewards` (a.k.a `R`)  will not exactly match jormungandr. This shouldn't matter. It should have minimal effect on the ranking, assuming pools don't have a truly massive *fixed* costs, or other extreme scenarios.
    - Our  `R` takes minting into account, but not tx fees. If there is no minting on the chain we're connecting to, we will estimate it to be 0, and pools will have equal desirability. [thread](https://input-output-rnd.slack.com/archives/GBT05825V/p1579694549014000?thread_ts=1579694010.013900&cid=GBT05825V) this will not happen on ITN.
    - `R` doesn't take the finite reward-pot into account either https://input-output-rnd.slack.com/archives/GBT05825V/p1579794144028500 🤷‍♂

**Comment by piotr-iohk** [comment]
@Anviking, should this go into QA?

**Comment by Anviking** [comment]
@piotr-iohk Yes, but I think I should look at a few things first

**Comment by Anviking** [comment]
Now I moved it

**Comment by piotr-iohk** [comment]
lgtm.
