### ISSUE TITLE
Make the wallet into a child_process IPC server with support for QueryPort/ReplyPort

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#144]
# Context

Daedalus (our main client) works by spawning a corresponding node backend process ensuring the supervision of the node. There are a few steps Daedalus goes through when starting a node as detailed in the diagram below:

![image](https://user-images.githubusercontent.com/5680256/55466176-f4492800-55fe-11e9-820c-eed33d686da8.png)

Among them, one is of particular interest for us at this stage: the [IPC](https://en.wikipedia.org/wiki/Inter-process_communication) channel. Because it's hard to choose a default port for our application (since on user's machine, another service may already be listening on the port we chose), we need the backend to be able to do a dynamic port selection (ask the OS to assign it an available port) and then, to communicate that port to Daedalus through the IPC channel. 

The current implementation of this IPC channel in cardano-sl can be found [here](https://github.com/input-output-hk/cardano-sl/blob/master/node-ipc/src/Cardano/NodeIPC.hs) and its usage in the codebase [here](https://github.com/input-output-hk/cardano-sl/blob/aca578c8b9500b8b043e51b395b74b93337d477e/wallet/src/Cardano/Wallet/Server/Plugins.hs#L120). As a replacement for `Cardano.NodeIPC`, we want to use the new implementation provided by the cardano-shell [here](https://github.com/input-output-hk/cardano-shell/tree/develop/src/Cardano/Shell/NodeIPC).

Note that, the name `NodeIPC` can be slightly misleading as it suggest it relates to the cardano node, but it actually refers to [node.js](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) here. So, testing of this IPC features can only happen if the launcher process is actually spawned from a node.js process (as an example, [here's](https://github.com/input-output-hk/daedalus/blob/develop/source/main/cardano/CardanoNode.js#L448-L452) Daedalus' current implementation). 

# Decision

We want to make our wallet an IPC server as well and support dynamic port selection (in the case no `--wallet-port` is passed). That server should only handle two type of messages for now:

- ~Ping: replying with Pong (to test the connectivity)~ no need for this.
- QueryPort: replying with ReplyPort and the corresponding port

In light of issue #368, the IPC server logic will be done in `cardano-wallet server` rather than `cardano-wallet-launcher`.

# Acceptance Criteria

- [ ] The ~launcher~ `cardano-wallet server` MUST listen on IPC commands when there's an available handle
- [ ] The `cardano-wallet server` MUST perform dynamic port selection for the wallet API when no port is provided in the CLI
- [ ] The `cardano-wallet-server` MUST use the provided wallet API `--port` command-line argument if it has been provided.
- [ ] The IPC handler MUST handle requests like ~`Ping` and~ `QueryPort` as described above
- [ ] The `cardano-wallet server` MUST die (and its corresponding sub-processes) when an opened IPC listener is closed.

---

# Development Plan

- [x] Either
   - [x] Investigate [Cardano.Shell.NodeIPC](https://github.com/input-output-hk/cardano-shell/blob/master/src/Cardano/Shell/NodeIPC/) code and check whether it can be imported as a library. ⇒ it's not suitable for re-use because testing code is mixed up with message protocol code which is mixed up with the ipc code.
   - [x] Copy&paste cardano-sl NodeIPC implementation ⇒ #388 
- [x] Call it DaedalusIPC rather than NodeIPC, because the word "node" is ambiguous and this protocol is unique to Daedalus.  ⇒ #388 
- [x] In `cardano-wallet server`, handle the case where NODE_CHANNEL_FD is set. In that case, start a async thread and respond to child_process QueryPort messages (from Daedalus) with the correct port.
- [x] In the DaedalusIPC module, handle the exception when the fd is closed, and gracefully cause the wallet-server process to exit.
- [x] In `cardano-wallet server` if the `--port` command line parameter is not given, start the warp server with any available port, and print that port as a log message. ⇒ #387 
- [x] Don't copy&paste across the ping/pong messages code because they serve no purpose.
- [x] The integration test will include running a nodejs program that calls `child_process.spawn({ command: 'cardano-wallet', arguments: ['server', ...], stdio: 'ipc', ... })`
- [x] Ensure the wallet API server is listening on the localhost interface only. In future, an `--address` argument can be added. ⇒ #387 

### Last step

- [ ] ~~After `QueryPort` is done, investigate how nodejs can send a socket object to the child_process, so that we can avoid having a TCP server listening on localhost (security risk). This needs to work on both windows and posix.~~

**edit (KtorZ)**: This decision needs refinement and further investigation, in particular for Windows. So, we agreed to open the discussion again in a while before we implement (or not) TLS.

# PR

| Number   | Base      |
| ---      | ---       |
| #387       | `master`  |
| #388        | `master`  |

# QA 

- A node.js mock IPC client written [here](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/http-bridge/test/integration/js/mock-daedalus.js)
  This basically simulates the interaction with Daedalus, also including illed messages to test parsing errors.

- Corresponding tests for the IPC server using the mock above are located in [Cardano.LauncherSpec](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/http-bridge/test/integration/Cardano/LauncherSpec.hs)

- Behavior regarding port selection is also described and tested in [Scenario/CLI/Port](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/CLI/Port.hs)

**Comment by KtorZ** [comment]
Closing this until we resolve the discussion about this topic with the frontend team.

**Comment by KtorZ** [comment]
As discussed with Daedalus, this is back up on the roadmap, so re-opening this ticket which is still valid.

**Comment by piotr-iohk** [comment]
Hi @rvl and @KtorZ. I've noticed that, as part of this ticket, cardano-wallet's `--port` lost its default value and currently one needs to provide `--port` on each `cardano-wallet` command, which is quite inconvenient. (Well, we had that before, obviously, but I was mostly using a default port value so it was not bothering me). 

I'm just thinking if we could `save` the port somehwere on `cardano-wallet server` start (whether it is expliclitly selected by the `--port` or randomly picked by this new mechanism) and simply make it available for any subsequent `cardano-wallet` command for the `server` session. 

In consequence we could drop `--port` parameter from any cardano-wallet command (except for `server`). I think it would significantly improve usability of the CLI. What are your thoughts?

**Comment by rvl** [comment]
Hi @piotr-iohk, yes good point. This change has made testing the CLI less convenient.

Three workable solutions I can think of:

1. Change the default port back to 8090, and add a separate option `--random-port` to enable random port selection.
2. Your suggestion - the server could drop the port number into `~/.cache/cardano-wallet/port` (and delete the file when exiting).
3. A "soft default" for the port - it will first try to listen on 8090, but then select a random port if that was unsuccessful.

**Comment by KtorZ** [comment]
3. is probably enough at the moment? It will be a sort of biased random :)
This is probably fine in most development environment and surely okay in users' systems too.

**Comment by piotr-iohk** [comment]
Sure, 3 seems reasonable. So, if I understand correctly, that would require also giving back `--port` it's default value `8090`?

**Comment by KtorZ** [comment]
This is how I see the behavior for 3. (@rvl to confirm if he sees things the same way):

- 8090 remains a default for the port, in very much the same way as it is now: if no `--port` is specified, the option value is `8090` for all commands.

- When starting the server, if no port is given, then we first try to start the server on the default port `8090`. If it fails because something's already listening on that port, we assign a random available port.

- When starting the serve, if `--port` is provided, then we try to start the server on the given port but, we do not try to assign to a random available port in case of failure. This would be rather misleading. 

In the end, giving no port is like assigning a random port, where random happens to always pick `8090` as a first random value.

**Comment by rvl** [comment]
I prefer 1 because it's easiest to implement, and avoids confusing behaviour if the user has accidentally started two wallets.

**Comment by piotr-iohk** [comment]
@rvl, @KtorZ

That lgtm. Few things I'd just like to clarify:

 - When running the test `DaedalusIPC` I see at the end of it (test itself passes):
```
[iohk.cardano-wallet.serve.DaedalusIPC:Notice:ThreadId 23] [2019-06-20 10:21:58.42 UTC] Daedalus IPC finished for this reason: <file descriptor: 3>: hGetLine: end of file
```
Not sure if that is a problem, but looks kind of strange/buggy.

 - `mock-daedalus.js`. I'm thinking maybe it would be worth adding `--random-port` when doing `child_process.spawn`, since that would probably be the use in the real world(?) (or maybe even test 3 cases: default port, `--port`, `--random-port`)
What do you guys think?

**Comment by KtorZ** [comment]
> Not sure if that is a problem, but looks kind of strange/buggy.

Nope, that's actually what happen when the pipe is closed between the client and the server, and that's a particular termination case handled by the the module already: 

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/DaedalusIPC.hs#L113-L116

Not that in practice, this would also terminates the wallet server which is the behavior we do want. It is possible to start the wallet without any IPC connection setup, but if the wallet started with an IPC connection, we expect it to never ends. If it does, then, we must also stop because it is unexpected.

> mock-daedalus.js. I'm thinking maybe it would be worth adding --random-port when doing child_process.spawn, since that would probably be the use in the real world(?) (or maybe even test 3 cases: default port, --port, --random-port)

This makes sense indeed. Note that we do not hardcode the port anywhere in the mock server but we do make a request using the port received from the IPC channel (see https://github.com/input-output-hk/cardano-wallet/blob/master/lib/http-bridge/test/integration/js/mock-daedalus.js#L47-L53). However, looking at the code, I am not actually sure that it would make the test fail if the port was wrong :thinking: ... I'll have a look into that and make the `--random-port` addition.

**Comment by piotr-iohk** [comment]
lgtm :+1:
