### ISSUE TITLE
cardano-node: Cannot send transaction on testnet (cardano-node + cardano-wallet-byron) 

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1462]
# Context
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | cardano-wallet: `2020.3.16 (git revision: 15d6b4e4d6a33fab19550581ddc967d2121ae537)`, cardano-node 1.8 |
| Platform     | Linux        |
| Installation | from source           |

# Steps to Reproduce

0. start cardano-node + wallet on testnet
 - `nix-build -A scripts.testnet.node -o testnet.node.local && testnet.node.local`
 -  `cardano-wallet-byron serve --node-socket ~/wb/cardano-node/state-node-testnet/node.socket --testnet /nix/store/7106qjwral616j6p5049m7hhi5ih0r33-testnet-genesis.json --database ./testnet`

1. Restore wallet with funds.
```
curl  -vX POST http://localhost:8090/v2/byron-wallets \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
"style": "random",
"name": "Byron",
"mnemonic_sentence": ["recycle","august","horse","awesome","shuffle","agent","almost","cheap","fury","speak","duty","enemy"],
"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```
2. Run TX:
```
curl  -vX POST http://localhost:8090/v2/byron-wallets/d3358ac0fc699784af021710e7aba2a3e31fbbd1/transactions \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{
	"payments": [
		{
			"address": "37btjrVyb4KFcfEEYyBU8j4VazP5he8iktF5uyD95avRpUHU6aWuLhuhGMmyFiJjtinJQPSjgGmh5w8qmuxDpHjK2JmCnPALuA4dyUkMpHF5Rf4PBd",
			"amount": {
				"quantity": 1,
				"unit": "lovelace"
			}
		}
		],
	"passphrase": "Secure Passphrase"
}' --http1.1  |  jq
```

## Expected behavior

Transaction is successful
## Actual behavior
 
Response:
```
{
  "code": "network_unreachable",
  "message": "The node backend is unreachable at the moment. Trying again in a bit might work."
}


```

cardano-wallet log:
```
[cardano-wallet.api-server:Warning:21567] [2020-03-19 17:06:52.77 UTC] [RequestId 96] 503 Service Unavailable in 60.54625479s

```

cardano-node log:
```
[piotr-la:cardano.node.metrics:Critical:115] [2020-03-19 17:35:22.87 UTC] txsInMempool = 0
[piotr-la:cardano.node.metrics:Critical:115] [2020-03-19 17:35:22.87 UTC] txsProcessed = 1
[piotr-la:cardano.node.metrics:Critical:115] [2020-03-19 17:35:22.87 UTC] mempoolBytes = 0
[piotr-la:cardano.node.Mempool:Info:115] [2020-03-19 17:35:22.87 UTC] {"kind":"TraceMempoolRejectedTxs","mempoolSize":"MempoolSize {msNumTxs = 0, msNumBytes = 0}","txRejected":"tx: Tx 4fa11b11460c93b1 with inputs [TxInUtxo 031e05b2 #1], outputs: [TxOut 40 lovelace -> 37btjrVyb4KFcfEEYyBU8j4VazP5he8iktF5uyD95avRpUHU6aWuLhuhGMmyFiJjtinJQPSjgGmh5w8qmuxDpHjK2JmCnPALuA4dyUkMpHF5Rf4PBd, TxOut 140199068 lovelace -> 2w1sdSJu3GVfNEJF5765gtMMP5koCgkxctKFdjhEh6S54B4zpDn1Rm7VL4wpYZEa5J5AfGyn93uxMTh1oP6AApYZ8kJNbBwbxJT]\nwitnesses: [\n    VKWitness: key = pub:cdf70c1e, key hash = 815fc0f5, sig = <signature>\n]"}
[piotr-la:cardano.node.Mempool.text:Info:115] [2020-03-19 17:35:22.87 UTC] {"kind":"TraceMempoolRejectedTxs","mempoolSize":"MempoolSize {msNumTxs = 0, msNumBytes = 0}","txRejected":"tx: Tx 4fa11b11460c93b1 with inputs [TxInUtxo 031e05b2 #1], outputs: [TxOut 40 lovelace -> 37btjrVyb4KFcfEEYyBU8j4VazP5he8iktF5uyD95avRpUHU6aWuLhuhGMmyFiJjtinJQPSjgGmh5w8qmuxDpHjK2JmCnPALuA4dyUkMpHF5Rf4PBd, TxOut 140199068 lovelace -> 2w1sdSJu3GVfNEJF5765gtMMP5koCgkxctKFdjhEh6S54B4zpDn1Rm7VL4wpYZEa5J5AfGyn93uxMTh1oP6AApYZ8kJNbBwbxJT]\nwitnesses: [\n    VKWitness: key = pub:cdf70c1e, key hash = 815fc0f5, sig = <signature>\n]"}
[piotr-la:cardano.node.LocalErrorPolicy:Error:55] [2020-03-19 17:35:23.87 UTC] {"event":"ErrorPolicyUnhandledApplicationException (MuxError {errorType = MuxBearerClosed, errorMsg = \"<socket: 30> closed when reading data, waiting on next header True\", errorStack = []})","kind":"ErrorPolicyTrace","address":"LocalAddress {getFilePath = \"\"}"}

```

---

# Resolution 

- [x] Resurrect (and upgrade) golden tests for signed txs from http-bridge / cardano-sl ==> #1463
- [x] Log messages from the local tx submission protocol ==> #1461 
- [x] Analyze log messages and figure out what's wrong.
- [x] Remove hard-coded network magic to mainnet in the API Server ==> #1481 
---

# QA

**Comment by piotr-iohk** [comment]
It seems the issue is not fixed entirely. Currently transaction is _accepted_ by the wallet and is hanging as pending. However it doesn't seem to be accepted by the node. In the node.log there is:

```
piotr-la:cardano.node.ChainDB.text:Notice:40] [2020-03-25 13:45:19.44 UTC] [589eb52@1057215] Copied block (Point 1055055, 27f42a02bfd6678e) to the ImmutableDB
[piotr-la:cardano.node.metrics:Critical:240] [2020-03-25 13:45:20.20 UTC] txsInMempool = 3
[piotr-la:cardano.node.metrics:Critical:240] [2020-03-25 13:45:20.20 UTC] txsProcessed = 1
[piotr-la:cardano.node.metrics:Critical:240] [2020-03-25 13:45:20.20 UTC] mempoolBytes = 1079
```
cardano-wallet version -> `2020.3.16 (git revision: acac18457f3bf7ad6dd811670994d00f5969c1cb)`

**Comment by piotr-iohk** [comment]
The issue still occurs on testnet:

`cardano-node 1.9.3`
`2020.4.1 (git revision: df83d3f54b96ebe9f516a7a216c0d1cc9f169aa0)`

Sent tx remains `pending`...

**Comment by KtorZ** [comment]
It should be fixed on cardano-node 1.9.3, but are we sure that 1.9.3 has been deployed on all relays already ?

**Comment by piotr-iohk** [comment]
Transactions are working fine on testnet now after upgrading relays to 1.9.3 and rebuilding volatile/ledger state on edge nodes.
