### ISSUE TITLE
CLI: Support bech32 encoding

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1603]
## Context

ADP-195

## Decision

Add support for bech32 key encoding.

## Acceptance criterea

- `key inspect`, `key child` and `key public` must accept both bech32- and hex-encoded keys.
- `key root` should still default to outputting a hex-encoded key
- `key root` should output bech32 when given `--encoding bech32`
- Chaining commands with pipes (`|`) should be possible.

## Development 

- [x] #1599 Add bech32 support
- [x] #1619 Render pretty bech32 error messages
- [x] #1622 Breaking: Only allow reading keys from stdin
- [x] #1643 Make rendering of bech32 errors more correct

## QA 

- Integration tests making sure commands can be chained with both hex and bech32 encoding https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core-integration/src/Test/Integration/Scenario/CLI/Keys.hs#L17-L51
- Golden tests for key decoding error messages https://github.com/input-output-hk/cardano-wallet/blob/master/lib/cli/test/unit/Cardano/CLISpec.hs#L607-L664
- Not sure if the ANSI red works on windows https://github.com/input-output-hk/cardano-wallet/pull/1619#issuecomment-624088900, but its just for an error message, and think there are more important things to worry about.
- Added two properties about the rendering of ANSI red in #1643 (but don't think it says anything about windows)

**Comment by piotr-iohk** [comment]
LGTM.
