### ISSUE TITLE
Actually integrate with HFC (byron-shelley) node

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1870]
# Context

User story: ADP-356

Creating this task for the actual integration with the HFC node, where as other tasks in the milestone are more preparatory.

### Questions

1. Q: We probably need to switch dynamically between the byron and shelley transaction layer.
    A: This is no longer the case - we don't need to support single-era mode any more.

2. Q: Can there be race conditions where tip is in shelley and wallet is in byron when we are creating txs?
    A: It does not matter how far along the wallet is synced, as long as its UTxO are spendable. For submitting txs, only the latest state of the network tip is relevant.

# Decision

1. [x] Update node libraries to latest versions (dcoutts/update-deps branch) ⇒ #1909

2. [x] Update cardano-node to 1.15.1 ⇒ #1910 or #1909 

3. [x] Move to using the new `Cardano.Api.Typed` module in `NetworkLayer` ⇒ #1909

4. [x] Move to using the new `Cardano.Api.Typed` module in `TransactionLayer`.

5. [x] Change network layer to use `CardanoBlock` instead of `ShelleyBlock` ⇒ #1909.
    - LocalChainSync - network tip follower
    - LocalChainSync - wallet block fetcher
    - LocalStateQuery - protocol parameters
    - LocalStateQuery - stake pools
    - LocalTxSubmission

6. [/] ~Adjust tx parameters query in network layer to include era information. This will be used for the TransactionLayer switch.~

7. [x] Add a network layer function to get latest Interpreter ⇒ #1909.

8. [/] ~Functions merged in input-output-hk/ouroboros-network#2399 allow for a single LocalStateQuery to be used for both shelley and HFC nodes. Attempt to support both shelley_testnet (shelley only) and mainnet_candidate (HFC) with this wrapper.~

9. [x] Integration test - launch a separate cluster for this test case. This modified cluster will do a hard fork. ⇒ #1924

10. [x] Adjust `cardano-wallet-shelley serve` CLI to support dual-era mode.

11. [ ] More details are yet to be discovered.

# Acceptance Criteria

1. Wallets must sync across hard fork boundary.
2. Transactions must be able to be submitted in ~both byron and~ shelley eras.

---

# Development 

(As above)

# QA 

1. Shelley integration tests are modified to do a hard fork before starting tests (`lib/shelley/src/Cardano/Wallet/Shelley/Launch.hs`).
2. Much of this change is refactoring which doesn't change behaviour. All previous shelley integration tests are run in the shelley era after a hard fork.

**Comment by piotr-iohk** [comment]
lgtm
