### ISSUE TITLE
Remove cardano-wallet-byron package

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1919]
# Context

ADP-356

With the hard fork combinator we have a wallet which works on both byron and shelley networks. This will be in the cardano-wallet-shelley package.

We no longer require wallets that can only work with single-era nodes.

# Decision

Remove the cardano-wallet-byron package.

Salvage any tests or benchmarks and copy them across to the cardano-wallet-shelley package.
- Restore benchmarks ⇒ #1695.

Note: grep is your friend, especially when tracking down byron references in the nix build.

# Acceptance Criteria

1. There must be only one cardano-node backed cardano-wallet.
2. Test cases, nightly tests, benchmarks, etc should not be lost because we need more automated QA not less.

---

# Development 

- [x] Add cardano-wallet-shelley restore bench to nightly #1695
- [x] Remove cardano-wallet-byron #2012 
- [x] Rename cardano-wallet-shelley to cardano-wallet #2013
- [x] Adjust wiki again
- [x] Ensure travis release script still works
- [ ] Consider moving `lib/*` to `.`
- [ ] Consider renaming `shelley` dir to `cardano-wallet`
- [x] Fix restore bench and docker #2045
- [x] Fix travis release deployment #2048

# QA 

- `cardano-wallet-byron` was removed.
- `cardano-wallet-shelley` was renamed to `cardano-wallet`
- Existing shelley tests pass.
    - Some Byron-specific integration tests were removed in #2012. Is this ok?

**Comment by piotr-iohk** [comment]
I is this completed? I suppose there are integration tests to be "merged" to shelley, e.g. -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/test/integration/Main.hs#L128, not sure about other stuff?

QA section filled would be helpful :sweat_smile:

**Comment by Anviking** [comment]
@piotr-iohk This is not in the QA column. Are you talking about another ticket?

**Comment by piotr-iohk** [comment]
Sorry, my bad. I thought I saw it in QA... Jesus :tired_face:

**Comment by piotr-iohk** [comment]
> Test cases, nightly tests, benchmarks, etc should not be lost because we need more automated QA not less.

Perhaps that is not a result of this change but Benchmarks and Windows tests are failing for quite a while now. (Although benchmarks are hopefully fixed :crossed_fingers: )

**Comment by piotr-iohk** [comment]
As per https://github.com/input-output-hk/cardano-wallet/issues/1970#issuecomment-672576025 this item was supposed to "fix" Windows tests...

**Comment by rvl** [comment]
The windows tests were fixed but then there was a new failure. I have opened #2067 for it.

**Comment by piotr-iohk** [comment]
lgtm
