### ISSUE TITLE
Technical Debts - Week 18

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#220]
# Context

Open a ticket to work on a few technical debts we've accumulated and could fix. The idea is similar to what we did in #94, and have a few bullet points of items that don't necessarily fit into any other milestones but still have some value for the project:

# Decision

- [x] (@KtorZ) [#222] Review Buildable instances for primitive types to be more readable & tested
- [x] (@Anviking  ) [:eyes: ] Add missing documentation to `Cardano.Wallet.Primitive.Types`
- [x] (@KtorZ) [#249] Review error message triggered by `generate mnemonic` in the CLI to display a clean message in read and exit with a failure code (rather than throwing with `fail`)
- [x] ( @KtorZ ) [Not Sure] Find private keys and redemption certificate corresponding to our local cluster
- [x] ( @KtorZ ) [In Progress] Allow redemption of avvm certificate in the integration scenarios
- [x] (@Anviking ) [#231] Fix documentation in the `Data.Quantity` module
- [x] ( @KtorZ ) [#223]  Get coverage report for integration test scenarios (i.e. run the wallet server in a thread and not in a new process)
- [x] ( @piotr-iohk ) [ #235, #251 ] Add missing integration tests for already implemented API endpoints (post, delete, list, get wallet)
- [x] ( @KtorZ ) [ #249 ] Implement missing endpoints for wallet management 

# Acceptance Criteria

1. Debts listed above _should_ have been tackled or discarded with justification.

---

# Development Plan

- Pick up a task from above
- Put your github handle @<...> in front to indicate that you're working on it
- Once completed, put a corresponding PR number next to it 

# PR

- #222 
- #223 
- #231 
- #232 
- #235
- #249
- #251 

# QA 

- I believe we addressed all the points written above ^^^ 
- We still have to port some integration tests related to transactions into our new implementation, but this wasn't really scoped from the above. So likely to be done next week.

**Comment by KtorZ** [comment]
Not 100% sure if those are the right ones, but time will tell. I'll try to make transactions coming from those redemption addresses:

<details>
    <summary>See Local Redemption Address + Private Key</summary>

Public Address (Base58) | Private Key (Base16)
--- | --- 
2cWKMJemoBaiFVqCFz8u5coqEfnrSB4FPGf7bcf1NmTrCf3nJUBSufmjSbKqvm5STgFyR | f9555ea827d77ceb6516851d04ac51f2e2d5cdcabb84ab182104bd227861b99c
2cWKMJemoBaiVawuYyrmXvmSSy5fwmHB1uYcLGr8nQ1E64YUe7unP76jyHCYVPeVFNw6y | fb2a386282e971fa05c4a2f20115fa5eccd04bfb83e6e9fe793667839b748d5d
2cWKMJemoBam3HMaHySGZBKGRq21tZmETW16rDi9cN6mxoxi2tpFwQLkH5EHpUJMwyBTr | d3fa850490e320c40318063fbca631d29b35bd8189e20fcc63f8a5f561cb95d5
2cWKMJemoBahqts3VDCfqLyCfVnDKw3qi8xF54cGD3hKne3UA9HZrxTQaU3drANuS2Ycy | d1c6171119cc91a4f8c646a346518144aa069a9be9904faeb2cc09f40cbc8304
2cWKMJemoBakLamoPKN5nJNMs7HSPmaLRxTB4YBfSVcb4xUiDrByHBjR9mX7nZ1kQPaMu | d6bb5a4b91024852a2c1971d81a3f902a2ca7784d5d074fdfc580f10f8b53cc2
2cWKMJemoBahRypdbnAQmCQYZVdkbp7QReNeL4VL8zcutfH1ZCKyxdyHdGZ7XzJV1xdyz | d6effd72cb2300188da112ebc1a06bb98bd829dd014381387daee6aa1c52d191
2cWKMJemoBah9Svm5UTD3dynnL5GABiZzUQ5wjb7YBkAsUShAL3N4iAV2ukxj8gg13XcJ | db74bf467eb83a32b3da99dea1e76985e7b5fa12fa2d50531be753319dd15e0f
2cWKMJemoBam7jusja7GWAvYE3tkGgBGVu9YKUMdUtcX2PXgaEUimiyznQF9tLpfeNUy8 | d9871a3abfe69abee49c38d9973648f677ddd00762146cecbf0e82cdc9931a51
2cWKMJemoBahbSd7bjvQBMbyaazdtjMaENG7eASkHy9QGJMszvYC4UErCruwCxuqqdrH3 | dc0c926a9f1ffea0b5db1bbcd0480d625736243e27247f8a10e1d1eeb9a62d4f
2cWKMJemoBajKbBpSXLL3532dyBShYyp6oqs2hH3HfwuH2tW7F67qrMB3Tk7Z4vzDtKyZ | e19e66dec8930ea4279453e4f36af21811432fe308af94022bc502abb346a040
2cWKMJemoBam9Qy8yZvhXQRcRjsaSjWj7ksne3TjMByzyBdxo9WbWvFpbspC8LnNvLCYA | ea1e6ce8e99bdefe1e7be0786f274d8fda3e5dc5db81d2d77c1c51f1b347989a
2cWKMJemoBamLpp5uHNrRwt2SS7vpJr6TQW4Khoicmj5FfUDgF8wdQ7yk8mjYjTpeMSU4 | efb0d21eba48c02291e9d22c99ccf074707afe1fa09b9b6a423653c093cdfa20
2cWKMJemoBahDtCgZgYrATdEa8mFdB1yxbrdue7hGwEaGnzw52JYpoF8jwwJU9du1H8np | eff7dbe9dbbcd31624f63839e61b4c06b14d51fc1dad524346cb6fa317221512
2cWKMJemoBakZjfkAd7bLSiKUgSrBDQnvFvAvLkdABtnuwtKKwrX8s5ujnDirzEwitP9N | f26988d2a04d7ddf8a997811baab6461b19b7df68f59afacdea01eb28c08912a
2cWKMJemoBaiCsfubGCHrXoCPQkhAMMnx1EGiB81yqYXzeXNGs4EfUVHs7SWmGUNNxpPA | f7c61feced10fc63e6d8ef595b71705b27a417d6688666f9d6946e9fa8e9a0e9
2cWKMJemoBamAuNZUnEY5y6n6FMepDY3V3zjv15ab4RAUNoMSkcMHwv9kQ7BAbfav2rZo | f6d4c32a246773512ca886428aaa8ee7344f01ea89a59b52806a0de882e62489
2cWKMJemoBakjUAqtTQn7YCVziEPouifL4FDoS62KNGwCWnyKrX93zrisjb8GESrYr4NC | 0164c0862f90a03cb0bbfdc7aa920abd23db676d1ce782a1e0ab358d2388f85a
2cWKMJemoBahHg9vacRrk3gGdkZS8J1iFE3mFKvQxtM2jKNz2mfo13TXDuXHFcP9Gc6FG | 077e1bfa7d183f028e423d78d4b57f4ca746458c24f02c9b993b3679c5f13a36
2cWKMJemoBaitDpjUcp3QMGqxpaHLNJU7z7MPG3b9FyuKbyWSuXWeQ1EonLR1GuWYoHUA | 0418583e85a3f057e21970e9b730d22fdb35175acc0a873017b99fa604de25dc
2cWKMJemoBairua4DLVF6jqj9269cEP97RyMkGw2DXfAXRpfT6QYB9XyiH9AXEEEi2T79 | 0578c88ae14bed310a6f6d8391ebea44fe3e867a3364d50b97540512fb91d6ac
2cWKMJemoBahgHHhVKwUm9oVg5RZxVWTfJW6rQriH57ncgLrPqGk8XMJ8jFDyxpx8Jv8C | 08c2e4bd3417f7f3bf1716cda299fb4195089b9f4e1becb2ca1a1b34aee993e6
2cWKMJemoBaihb5M75gML1VbXxSnrXQoLBXgKdPE4BndbEpWTanPikaFwLxVu4EJe9XW3 | 0fb13cf0aa5e96ac85c2cf9e4fc87cb658ede4cec6b5fb6120a92f40cb6d903e
2cWKMJemoBaiyPyV1LqdcyaLCgKysNhYD7dShmzdxZf88mvMkzk9t3tEfsTSDXrLEt3ZQ | 1221ea676fe82fdc733d4905a289f8eb245caf489a5361cb21b8801aeea104ff
2cWKMJemoBakJxPTG2s2TQGRxdhegb9uzUHXCRMXiKR7DZ4t1UtJMWA9F6ov3mNfMhqRd | 14f3c8bd7aede00f2234132f51ecd44b05023a4fee1c33594189c4ef3b19f603
2cWKMJemoBajBcncsG7uAenwSJbVfo2gjzcQYxNzRsTvXH5SrzeZY94zkV77zFcaM9gGz | 1fe5f3b3407dd60c4f0ed907ec1b87317c309c508dc25ad13d1667b4fc0289bf
2cWKMJemoBahJ1fPSfBUsvEGbsNropMLjVEcZQAYUmQ3nG2RwjsZXPqU6AtwRu2PNzBFW | 1f409dbc83e3af356d0564d7542dd88d0175e3e9af39f2dd740cfd7e948a0ce0
2cWKMJemoBaiQt6mFrzB2LKsdYtYrksepj6LGWX3WP3hYTuCxYMJ2jLA5evBnKFJ8zqAn | 1c4892ed84a71d1acb31405d9e9e9ca238618d421855896dddf12a0fbe83e303
2cWKMJemoBai8z4zPcg1HuUYwJ1jBy6junyspNgZhMVHJG4oT1YMRUbBHRZgMTaEoB7gn | 1f1a67df7f2a56f94f83d59809bb1380a5afd1fe98132eea7f9e7846f87934ef
2cWKMJemoBak7RhekwfB7ASBomvVEbCkWzbhuxukeG5JBPhCjUj74TjL9v6RRs6KNV1mT | 21b0c0d3a09ed14ecfc595c3e23d3ecdd105ce5576b33f03fc6b9237feaf20a5
2cWKMJemoBahkRbaTnLk9ZA32AqzFWyPwB6zjLwXfemYZ1t3k4rCS95r1EZPYzSAL4Zmq | 246751207679a829ff65831ffa98825bdf30529364d6f1affb3015baaf130054
2cWKMJemoBajpjHsnWheqxEwoKt7rGiKh1kPpWdYXHZLwJEShfRiWLLCE3uXHquAyVWGP | 247e88835b07a1a625544af8599cab29d1082fa6da930202482d1e0423d42d52
2cWKMJemoBakDSAZTcMP9WKkE9WSzm1aEKzHAeM73WLY9LAGkMLG5B2J8civdtMTh7X8L | 24ed3dbd0abf96851a8d66237eacb34867ae452959301c0708d6c54d383723a7
2cWKMJemoBaitHZq2ebs7sPLKavPoKy2wwf4gYSezyneqcfm6DUtKS7CyceUhVr9wBybT | 265332802ea34bb513a05e0e155afd2ca9b7fe0314f38ef305316be2fdcaee62
2cWKMJemoBahSRNTUJmtYje3HfXQAcqFPmwtVDbLU1iUAfefRrZ1zg2HjqjDju2D8rq53 | 2b480726dcae6565c026316c20a0d1fea97e5c6d3e6145de2f9e587af4c4bf17
2cWKMJemoBaiQWchT4U16hKNQMz25gqgegapjuARG2Dw657TiNhXZ3sBy2w7XbrpnUD81 | 2b578ee4255cfefc82be0ecfefcd35317cdae3b1f507c174f193207d5815b33b
2cWKMJemoBaimsAwKZ5bRaS6CpxnLaFdyH8RLaWjTmsFVqhaPH8hi5kWvQ9VcVRxmLucW | 2841e0954a89c65cdcff1748b3e2ff367b2a270645503b8567e5f9097f56b5ce
2cWKMJemoBakeSSUgPasewc11Y4Fc5Ac5vBPY2hSBCKZ6aiRadHzG8ngTEsizaviZSUht | 30c8797f8fd7971045d58b599217464fc3ecb03f8b48c29631a4edb4fc54c3d9
2cWKMJemoBaiMcxdunH7V4mnWjsEKSQK5REHcVGhLQrfT8sZvYXoLaL5pkxYWkAJNQpbV | 311a4a3521675e201455e9df93f3f005b03ec5111daf39ee258432b01e445d57
2cWKMJemoBaiCPLEUEDT4drmxE9dtyCEYRkspTYZN46GCSZ72csXoV9v2z29VxTgB7kJF | 3306495a8fac0be73e1d97f45bd9f67a731eb0d03e038d9b4044aa7acdd201ec
2cWKMJemoBajs9PZgLvJwZ8Hx2b7jqz1E7VCbHoocbezHmNd4ZLThxkVorWBCovm7BHgW | 36f3272698b542a4cb1a9db342bd0888cc4eeaa2a9518b4f0291124cca2aa34a
2cWKMJemoBaiSXKev4VHbCcHfT1b2AAzYvEkgwCYxH7USwHFyr5NegxJMvWdZGRvFvdfU | 3bfd53bd5dcfea3f6e88f8f6da9d85902fe9fda068960faa47fb11f13acdac39
2cWKMJemoBajaYXWjUWhW1LJJueZ3BgD4hceS8otPjN4GrpvANys8fUeX2nEi6CSMXvGA | 3a0d7c820d75642dac5f31f1a5ad435da5729c5142f7bc772584c86cb22e7bd9
2cWKMJemoBakp7Z7nbDCmfrzL42UwuGJfLj9qziehkXePaG9N7a8SyvrNqAPP8Lwnov45 | 3a98bc422a25395e70e1b758b2e1b34c4f4e761529efa3d3d8d6f9e10df460bc
2cWKMJemoBajkTwvjC1hDkpeAfRi7GqAA9yjUfYmDQNQukL9KRDKkkopuEn3xobznGzMM | 3f43f23a97b64dbcef2a457041467e44d68c1bea162dd5a48abbee05af5627f7
2cWKMJemoBaiwAMgMEYXEjXVCGRtih9cF59ZybcAkBXuLzJ2ZdC96bxKA3E78UfgvfRGk | 3cab0874c3b104f756b975901826ed7023738334ac4b83b260ed66b922d1593f
2cWKMJemoBakfqXNXcgBW8xzFfgJx7Sur9uN5qyW1VGNTeUAyyntD6B7ZXzfKyrnGYcRF | 3dc1185776c1c9bb06f3eaef075d2a9002de6775ca532710b4c8c8343d62901f
2cWKMJemoBahdRueLPVHrpcCiBuKLgLRvH4kFNkrLtitvw64e8hXuFidgF1BJeUcNXw5H | 4335bc430f6a7d4889fc29c0ba23dc69e14c63e5b8c81eedab65c75a4db15e33
2cWKMJemoBah9AkDMvkYc5ZR9ALVgjHmereGJ12UMfYWer8R4Uee32AgxEn2tiqTFNr9y | 4bb3b8a5aca65f81bd79283d4409c3e7c299ec1b063e24237b73ed0efc45a2de
2cWKMJemoBaha3NUf4QjbuCgxC7u1GN5aTayeTuTUoCuyEhWVUycTjiUQFgSrwoZzKdzm | 4a153741dcf4d768c6912120f11ed84b034e0656bfcda71eea4625b9b8e2be91
2cWKMJemoBaiWUJ6QNJ6PbWJVMj7n3ZKHzXdpJjHzt4vfVWbgisFXGjgHUHzBrs2T4gi2 | 4a8f64dbb0069420c54741b15d23ead295d352672b000c7d878996f10d1601c5
2cWKMJemoBaiPJQQxGG9izUxdNbyvd3jGUYrfgwEdeqDWxCa7Pt5PZ5yXmjbPWjPzE4A8 | 4acc809280661e62ce77756502e5fafac42107d1a2164975e431b1429d603b45
2cWKMJemoBahrDocJaHCbb5LHChhDQZgEMdGrEdVFdZGbeGWqKYB4Lvh4BTvmNUFDvWT8 | 4c0d00b357f82c4157d9b0fd291881276175b76b1d9aaf1a1a5ba641c330dda6
2cWKMJemoBakUYywUB8LWWPCkA65AayYbSLazFWvRdUXPbhaLKJ1vs7gQiAujh2m4VumN | 51151c606c3f55aef67df29051086bcf757c3be436fadcd30c33349df7e08786
2cWKMJemoBam8MXSEDwqJFY26MWhPacasNChqdXNgT9zrAKmfcfinBsUsZjtkVRjnNVhC | 54aacce9691f0c8120c4129726ca8a200bd78f10e084b8c3a8b5fe8dad791de6
2cWKMJemoBajM5cCPv7rJNDhknjoRsgNFwNJu3Pxzh14qDYwvcBKzk8QC9UNFCzGkxmMz | 587a0003f2654014d207ccc37c79e4c18314e4c3a6c5ebc2286b76721dd4eb6d
2cWKMJemoBakezBGbgg1P1JRtRPF9iKNtnGM8nyTo7xLugsMEw4Qt7Xq3hhLjpNzwwK46 | 58e155f7bca0fc65c36850cd99a737bc694a7fed654539a832707e8e6534171a
2cWKMJemoBajNBDp44Fxmfzhpr23qWFghSuN4jk3eUPNN1D44Grb1PZjyU3jS61PitrBH | 59532b15aa97a31acc5bde7752b29f607dadefdddec3350714a44170ee264a14
2cWKMJemoBajZYgDd3aNpXaek2M1weqXA8UPeR2cmLkasHyq4byxvsbSqzFyPKgKFzG7m | 60bfb941b2c43d51cf6a1d79604aeacd8176d8be15e599ec1bb40fe5acea3927
2cWKMJemoBajryrRGP6EitPK83XQyBS4tibL7tauVZCTaMbRw5L5NaCL6CtGMrCwTqkLZ | 620ac3cd426b89936168c1647bd222f76fd53ff369cda29e15e6351775824025
2cWKMJemoBam7nV1D2NCvY7AAaEoa6kJWscgoaB52wy3sjAvGKtDZySh18Lin2NbVQjJz | 628b60a47c24967879a7e01191878805e30d9f216cd72a8d49e23ca04139e59a
2cWKMJemoBahWaUWBHRQCS63W3kyBQQDhtJd9abqqewyrpks3pCvg7Lu6xrtqPpahucPn | 65276783a367d7e5d669a3487dcf8e89a1abea7d622cca4e033a291b8c96ef40
2cWKMJemoBai8XvfPUbLdtisyk8xg9UCyfQoGdUQgpHMHyvFvcPuGPAYeYt2fZEvg87fR | ffc6012ec4d676c535dd66af4749746188804ae81ade32aa1bd2f677033949f0
2cWKMJemoBakn6ZmS5KeCoi6dpBXWiDWXC7o7fNoKrR4uVhF3J3u7jdzWEoEC3PuQgrku | fcd66a5166a5cfbd6533b0219d20664076f0f764dd95b6f71d0bd00e4b984354
2cWKMJemoBaiSK4Z7tjckTraf9wp4og9QTETBczUVJdourBe5YfW3e1XKje15ubVpjpQT | fd94bd709f10e9bd6495ffb37e4a73a6f6cf2a9c1e084dba88da79cdab72c2da
2cWKMJemoBajBKN1yHvsvg6DctLkno8UAMB4PTdQw5p1c3oaD9U5jFctnrirttxKFidnz | 68993fa5f9fdb9e74b51c1a2ea9aa080711b8dbb3f56f90820d0fd5f399c2c4e
2cWKMJemoBaiQpxHrnUEdYa7ddrfVvs5ynHAaRivL1U3Vokq3xVdqqGGpCteUinyvsy9S | 69af13e42a6f4fd877ff0dfd7874d1455226e27f3f06d765a3e86e38ca72cdaa
2cWKMJemoBakJQxSxnn6JgGiefzon8raX4yPcZTKv36fgEH3njuCjioYYaZJWi6kdapL6 | 765d47a7be6889401a91c380757d78e369a52be9073334eaf980ed72bb58aa45
2cWKMJemoBaksD3WKqemeH8p8uvYKP8uDG4tZYDCwDeZVSbUrTnhixWKSuka93NV5uiig | 76776fb216eb8bc2647aadbe37cf2f0997535d505e1155ab9861bb1ca0a1c8c1
2cWKMJemoBakm7XxNmeznok4reyTmGVGbjXxXfk6bAAVKHHKrB2ag7qSjaDXNDGqphUYB | 76def88ba61ce23e0213f2a79ce86254352c7cfee90ab06b27d3a3ad69aacff2
2cWKMJemoBai5cFNQV73AsKZDXmZ3FcxNaJVjVfoQ39U5dmwwCHRsg22LWzaGU4XUZcwL | 79be6916cbee0442bb900b675c0ce1d3ea8ebd509f2ffb51a48660eea8e47a11
2cWKMJemoBakY1ymRKStAbYtXcMeFrzygjkf8xzSsjatAG8GtRyfAakevzEw82mW6jDLh | 7aeaff2e7c89ee7fd06281763a86f1fc2028d0f124549f8d946ecd4004ab02df
2cWKMJemoBajySLcJrnTMtCoZ3NPg1AiA9TKKEmyhcP3sFkNgjAhLtKxy2XxdzQsUieWy | 7fa220256d5e6b3dfbd7923f4f6d89d7b4bc577f9dabb135d7689805beb51bc5
2cWKMJemoBaiziZfmWuRbt8boeZjmX6dTwQTRoB4qXhiU1HKk9gzQdrEu443ia2rHL8x6 | 809d823b92e0c30c8a52edf29f980210864aeb4449379b06aadc818317b63056
2cWKMJemoBahL9VsCPXS2iEZkFg3DPEhs4yNNKsiGPZti9jnc1fc1kwZ2iFRXyFBaBS8a | 8bb068be0ad1c8a93a7b54f632e57133ebb46da0c832e47f6f8953b8d8dc4d6b
2cWKMJemoBam782EUnZ5smDUHa4DTygUUDFL8sZ5cTY4qS69TYRREUu9a8ACHDjs3Wc4N | 8b044baffac50290a3857afb6344e022d12a43d326c1a125cacab3b67dc20a5b
2cWKMJemoBajv6iAiKTi6YsoU1CSMy9Q93EwbZkttmvfdLCoAy1Km83m4Y9kSkgkvrMfE | 8da8b84eb262629d359be84550b8cbf129875d63f8fd989e032f80b7c98551c8
2cWKMJemoBakSoTNY8mMsMFLoTKfC8Ev34vwsic4ZYZq4SdSDQ8kEhvHRKnbLqF7a9YBs | 92b525b776d8a272d447f5bf90f6168a241a739efe225aa38cf6dd308bc39251
2cWKMJemoBakriUeQkf18vopGKuNSoa8LLs5mADYWLR4xpRe42CEgYJPEM9FY1uz4ury2 | 93300e9a2b3bb06a8207bf20b0e4688242290b59e374edb9e7f94eafedc15812
2cWKMJemoBahB91Z5SvXSBF3ukigTZFmeFASr7oAg7Bh5U5rneR6FJf8nqDhdvCqx1RYJ | 96a5fa56e6cc018ef4f6fa1006cd26bca45a298dd90d1017728070326ae05745
2cWKMJemoBahD3e2TjDsAydKdayHLDCZMU5Gwk2uS2PPnEieW39CL6D6Gt1RDGctixHnx | 97180d108d2b5ea25607786776bb5524af8dfac242ed30a20632158be3f7fef1
2cWKMJemoBakmcYisRSjPufxtuAzSh9goXvZAwdiYEyetsyBHiNctEr8yMHjZVVqxwe4K | 9b3ffec3641e2782cfb152caad6dc41e90a481742be2d735c51f010f3be30c50
2cWKMJemoBakENUomQpxa4P25m4ReUuG1FoXWeTetrtbx6LQCJqSc1e3bqhBqXXjQNSGc | 9cd749c0fa8ccea1f0c185043a6d788f5faa148fd2b15633c813f42adaa79624
2cWKMJemoBakMsLhgwKgUjxF71wnEt3qf8tbV5ykMK4ncGixE65UDmWPpZ9GCBoP8eApw | 9e653cef8a863391ed9942a368f218925c9f4ea1b5a08d03d719974b29822f1f
2cWKMJemoBaiWiQSQXZDVtfm6VSGdAT2uJXPAU5H8exkAJMFt2f4xNfAfVBSfPKsyfqev | a9f492923d0d5a97c00a0b0d5b53c3242ede7fa9485d9293c4362234996725cc
2cWKMJemoBajyVSzT9fzF8iioYii9y4YZpqv7fRnPQSHS95VZHdVwd3mPetqFY3oXGSaq | ae82c176056d8a881ee0bc91d4ac5480c7abce4dde63cee1754f5d5647a55822
2cWKMJemoBai1NnGUHuiMwih6q295JRpc6q2UqufMZMJ9624x6s7Zzb6KV2w5oSh7fxMZ | b21e3dcc1363826f8214507f3effa355e06f70719479ece272454295a0dc25c3
2cWKMJemoBaiG5nQETZ1mKmL2rEA95D4iqyDLVBjsrAgtRjGQs2cF8n3vXaJkpGFaCWYM | b2d0bfc74e63d42f226d164dbf1b4057cb9234ec279d09f999930ebc3e1691dc
2cWKMJemoBam8gXvmkfF4hiByX7ahcJHfocW3sMFM84gJmuaTTc4gUFgGvDAgoGXSJqRC | b6cba525af74a11a0edb4024953e7dba0cdcc22f55e795dc1cbb1da655b5507c
2cWKMJemoBah9JJfHvtPMzL6qS22biDkwU3EY8unwzTd2im6j5oCWaLScH9Gp3GcQpgBh | b9d9acc1828fe5c40298fb324de3e1b972ab598dc3838f9bfaafd5f713eeaf72
2cWKMJemoBakEGZvQkKtEJr1GCv32Fwd26cuvxCcNQwNU6fh87CJSRdEtHgQJURuRaZr6 | bc1a4fc424681dbef747c26296c5602e07036f9af3bb56aebbcac0cd7337628e
2cWKMJemoBak3diYxiGw82GUqWfPfigBtiFGgKPJSeSQraZ47RdW3GtAKbH5ZxoDcDJm5 | be46583ffa23e09de3b65574ab8846abea53e8f83c5e53f31ea66137d92a1218
2cWKMJemoBakvbzvHbNBHojnzC6agUn4LTv5byzp9pWFSW7zahp2neDzRynPYYkfNFesF | c415c6da356944cac6adef9c1ed44dc81953db0066ef39480983d57903509417
2cWKMJemoBajDaKdzQXNgyEqzwVLqSyTk2ig5zzquQVW7mYci7nc5XqNeYQKwR59a7jkS | cbe9b4b12e622776f1f38e2444e8e6410806f4331b5de46c04d3beacf721a107
2cWKMJemoBakjaf9C63rrZ3Kd64EsCW4gdToe8Sy1VWbamPCSuatwsQwHNAEo3mpgwS6q | cb78c9c7bf73e2be6dbb11d916bbb1b79e762d829e1e6c6ced71e15e0ba02d09
2cWKMJemoBahvpNtWAwanTMuecYpxWCQZvHW1EYkwxQXFxjwf1ZnTcp4W3u4XhgkRq6F8 | c9f7d2e616900395a58402201757edc72207342b3a45cef8618b0f4959962f78
2cWKMJemoBakQ1tiXfnS8TivUfNGEYFxW5zQWyENpkP12wt2V5H1GbEaufwiz9rsUHJqe | cb283a4652a167d291dcac51f2c80fc2f840828880fb22d34cecd13563f75afa
2cWKMJemoBam5NriwwWKxXmNY2gysdU7kFWJ9snidyiCJYDzhzJMzb4R75taCWnwQURUi | cf529f1124817bebacec63ec9826c8df7544c2b666c5b27c06f662af3ad9a73d
2cWKMJemoBajLYWB4usnWCbMYjvtyerahM5o5mc7AwzuxEJKZPDQSH4pPrAXTKEE3n6g6 | cc45d4f94e4cf02a0c8c6ce7fdad6ca7c86cabbb278da5f6b5e4257778690302
2cWKMJemoBahQiDBaq9ttww9Wsvgk3Mp7GLybrsRFHJ21yCmYuwLfkUpcWHJPm5K5A9u6 | ce6a3a6a518215d79081c0bd9017c28498f8f86638f29eea1c437790a57d081d
2cWKMJemoBajFuFtVTdgXftNJ3hPBStvvA9hLTCvZwnhapn1LEyD6gbEecdL7SiQy34MJ | ceeb76750d8cd9e8a012534babeb13597cc7fe3eb32305c452a1a067371282e2

</details>

**Comment by piotr-iohk** [comment]
:+1:
