### ISSUE TITLE
cardano-wallet CLI - few issues to be tackled

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#229]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Linux | Code  v Configuration v Environment v Human v Unknown |

# Context
 
Bug to gather and address some issues that need to be fixed for CLI

**Need to be fixed:**
- ~`get wallet` doesn't work, prints out `Something went wrong`~ fixed by #230
- `--version` doesn't print out anything
- `--port` is missing on `delete wallet`
- `delete wallet` does not print anything when you put id that does not exists and prints out just `[]` after successful deletion. I'd expect some more informative messages (e.g. `Wallet not found` and `Wallet deleted successfully` respectively)
-  `cardano-wallet get wallet --wallet-id=457570f4c6d7fceff6f6945711e710f3ea008433` - wallet id that does not exist prints out nothing (same as for `delete wallet`), again something like `Wallet not found` would be better

**Might be addressed here**
(These are not really `bugs` but some ideas and at most _usability_ flaws. Some might be addressed here. Anything not addressed here should land on the list of [Ideas](https://github.com/input-output-hk/cardano-wallet/wiki/Blackboard) - however let's discuss before tackling anything from here, as there are ongoing discussions on whether we still stick to `docopts`)

- I agree with @rvl to make wallet-id a positional argument (especially as it is now not consistent --wallet-id (on get wallet) vs. --id (on delete wallet))
- I like the @jonathanknowles idea, that would organize things nicely (I had _similar_ approach on `cardano-wallet-legacy` when created a script for aiding some manual scenarios https://github.com/input-output-hk/cardano-wallet-legacy/blob/develop/test/manual/scripts/wallet.sh#L3-L11, btw. `wallet-id` is also a positional arg there, and in particular for wallet get could be optional `wallet get [<wallet-id>]`)
One alternative that I can think of is put the noun first:

>`cardano-wallet wallet get`
>`cardano-wallet wallet list`
>`cardano-wallet wallet create`
>`cardano-wallet wallet delete`
>`cardano-wallet mnemonic generate`

This would have the advantage that we could support different "levels" of help. For example:

>`cardano-wallet --help`
>`cardano-wallet wallet --help`
>`cardano-wallet wallet list --help`

- I like the idea that `passphrase` is hidden with `*` but I think there needs to be another prompt for repeating the password (as pointed by @KtorZ)
- for mnemonics I think I'd rather leave them not hidden with `*`. I think if someone would try to write them manually it'd be very easy to make a mistake (as already pointed). In practice, when creating new wallet, I think it would be rather a copy-paste thing from places like https://iancoleman.io/bip39/ or simply copying output from `cardano-wallet generate mnemonic` therefore, again, hidding them does not seem to be very useful.
- generally I think that `create wallet` could be made a responsive CLI for all arguments for consistncy (currently `--name` and `--address_pool_gap` remain as inline arguments)

# Steps to Reproduce

`stack exec -- cardano-wallet`

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

---

# Resolution Plan

- [x] (@KtorZ - #230) I'll start investigating the issue with the `get wallet` command
- [x] (@KtorZ - #232) Rework the CLI hierarchy to put resources first and add missing options 
- [x] (@Ktorz - #232) Implement `--version` using the version mentioned in the .cabal file
- [x] (@KtorZ - #232) Make wallet id argument positional
- [x] (@KtorZ - #232) Implement better response handling for `404` responses and delete success
- [x] (@KtorZ - #232) Prompt passphrase twice for repetition
- [x] (@KtorZ - #232) Do not hide mnemonic when typed
- [x] (@KtorZ - #232) Do now show ANSI colors if not a terminal

# PR

- #230 
- #232 

# QA 

I think every points in "should be fixed" and mostly everything in "might be fixed" have been addressed. See #232 for the complete list of things that were done.

**Comment by piotr-iohk** [comment]
>(@KtorZ) Implement better response handling for 404 responses and delete success

FYI, same thing for is for `get wallet` - I've added bullet point to the ticket description :+1:

**Comment by piotr-iohk** [comment]
lgtm :+1: 

Few things that will go to the list of _Ideas_:
- if the passphrases don't match - prompt user to put them again twice
- make wallet backend server introduce itself in the HTTP header `server` (and make CLI to check for that value and put some warning/error if it don't match)
- `create wallet` wizard to be a whole responsive/prompt CLI
- different levels of `--help`
