### ISSUE TITLE
Technical Debts Sprint 27-28

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#460]
# Context

This ticket is a collection of small tasks to be done during down times to reduce the technical debts. These are small things identified by looking at the code-coverage and logs. 

# Decision

- [x] [@piotr-iohk] [#489] Testing missing or invalid options in the CLI (key, not value)
- [x] [@paweljakubas] [#540] Send a transaction from valid but not owned addresses
- [x] [@KtorZ] Enable code-coverage on the IPC tests with the mock Daedalus
- [x] [@jonathanknowles] ToText/FromText roundtrip tests for 'Direction'
- [x] [@rvl] Test fetching block that doesn't exist on Jörmungandr ⇒ #525
- [x] [@rvl] Test fetching blocks from an unknown parent on Jörmungandr ⇒ #525
- [x] [@rvl] Test sending request via Jörmungandr network layer on a not-started Jörmungandr backend ⇒ #530
- [x] [@jonathanknowles]  Visualize `Show` results for errors of the `NetworkLayer`, `DBLayer` and `TransactionLayer`
- [x] [@KtorZ] [#539] Investigate SQLite numerous `DELETE` requests regarding the address_pool ids 
- [x] [@paweljakubas] [#527 ] In cardano-wallet, the `restoreSleep` function sleeps for an arbitrary 10s. It'd be better to sleep for a duration based on the slot-length (half of the slot-length would be nice), received as a parameter alongside the `FeePolicy`.

# Acceptance Criteria

1. Technical debts above `must` have been tackled or, discarded with justification.

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #525        | `master`  |
| #527         | `master`  |
| #530 | `master` |
| #539  | `master` |
| #540 | `master` |

# QA 

- Code coverage now enabled for DaedalusIPC: https://coveralls.io/jobs/50735410/source_files/1383127890. The trick was in fact that tests were only ran using the `launcher` and somehow, we don't get coverage reports for anything that happen on the server launched by the server (probably because it's another process which escapes a bit the coverage realm of stack). Running the same tests from the `serve` commands collects coverage as we expect.

**Comment by piotr-iohk** [comment]
Just to clarify:
> Testing missing or invalid options in the CLI (key, not value)

Meaning more tests like this one? -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/CLI/Mnemonics.hs#L37-L40

> Send a transaction from valid but not owned addresses

I suppose you don't mean this? -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/CLI/Transactions.hs#L319-L333

**Comment by KtorZ** [comment]
> Meaning more tests like this one? -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/CLI/Mnemonics.hs#L37-L40

Well, yes, also for the multi-args parsing (like `payment...`). I was surprised to see the corresponding function not covered although we don't count partially covered lines as covered and we don't see whether lines are partially covered or not in coveralls (so we'd have to check with a local code-coverage report to see exactly what's not covered regarding the argument parsing, maybe it's just some unevaluated thunks..)

> I suppose you don't mean this? -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/integration/Test/Integration/Scenario/CLI/Transactions.hs#L319-L333

No I don't :) I mean, using a valid basse58 or bech32 but that was generated from another wallet. The signing function should fail because we don't have any private key corresponding to that address.

**Comment by piotr-iohk** [comment]
>I mean, using a valid basse58 or bech32 but that was generated from another wallet. The signing function should fail because we don't have any private key corresponding to that address.

I suppose it cannot be covered using the integration scenario? (as you provide a wallet id as a source of transaction and address as a destination, so _Send a transaction from valid but not owned addresses_ would not be easy to do with this)

**Comment by KtorZ** [comment]
> I suppose it cannot be covered using the integration scenario?

Tricky indeed since we don't _yet_ allow API users to specify their own inputs. This can be covered at the unit-test level however.

**Comment by Anviking** [comment]
Aren't the following two cases covered?
> - [ ] Test fetching blocks from an unknown parent on Jörmungandr
>  - [ ] Test sending request via Jörmungandr network layer on a not-started Jörmungandr backend

https://github.com/input-output-hk/cardano-wallet/blob/c9f19dd0856f44f6882156edc79d99217fab16e0/lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs#L113-L137

> - [ ] Test fetching block that doesn't exist on Jörmungandr

To avoid testing `JormungandrLayer` directly, maybe we can provide a mock `getDescendantIds` that returns invalid ones 🤔

**Comment by piotr-iohk** [comment]
lgtm :+1:
