### ISSUE TITLE
Add API endpoint to restore a legacy wallet.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#774]
# Context

This task will provide an API endpoint that allows users to restore a Byron wallet from a mnemonic sentence.

# Decision

The API will provide an endpoint similar to the following:
```yaml
/byron/wallets:
  post:
    operationId: postByronWallet
    tags: ["Wallets"]
    summary: Restore
    description: Restore a Byron wallet from a mnemonic sentence.
    parameters:
      - <<: *parametersBody
        schema: *ApiByronWalletPostData
    responses: *responsesPostByronWallet
```

Where types have definitions similar to the following:

```yaml
ApiByronWalletPostData: &ApiByronWalletPostData
  type: object
  required:
    - name
    - mnemonic_sentence
    - passphrase
  properties:
    name: *walletName
    mnemonic_sentence: *byronWalletMnemonicSentence
    passphrase: *walletPassphrase
```
```yaml
x-byronWalletMnemonicSentence: &byronWalletMnemonicSentence
  description: A list of mnemonic words
  type: array
  minItems: 12
  maxItems: 12
  items:
    type: string
    format: bip-0039-mnemonic-word{english}
  example:
    [ "squirrel", "material", "silly", "twice", "direct", "slush"
    , "pistol", "razor", "become", "junk", "kingdom", "flee"]
```
```yaml
x-responsesPostByronWallet: &responsesPostByronWallet
  <<: *responsesErr400
  <<: *responsesErr405
  <<: *responsesErr406
  <<: *responsesErr409
  <<: *responsesErr415
  202:
    description: Accepted
    schema: *ApiByronWallet
```

# Acceptance Criteria

Within the list of criteria below, a _**ticked**_ criterion indicates that there is _**test coverage**_ in the `master` branch to demonstrate that this criterion is _**satisfied**_.

- [x] The API _must_ support restoration of Byron wallets through a dedicated endpoint.
- [x] After a successful restoration, calling [`getByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/776) with a restored wallet ID _must_ succeed.
- [x] After a successful restoration, the [`listByronWallets`](https://github.com/input-output-hk/cardano-wallet/issues/775) operation _must_ include the restored wallet in the list it returns.
- [x] After a successful restoration, calling [`getByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/776) with a restored wallet ID _must_ succeed.
- [x] After a successful restoration, calling `postByronWallet` _again_ with the _same_ mnemonic sentence _should_ result in an error.

# PR

| Number   | Base      |
| ---      | ---       |
| #790 | master |
| #817 | master |
| #846 | master |

# QA

- [x] Build integration tests to check that all acceptance criteria are satisfied.

**Comment by piotr-iohk** [comment]
lgtm!
