### ISSUE TITLE
Add API endpoint to migrate funds from a legacy wallet.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#779]
# Context

This task will provide an API endpoint that allows users to **migrate** their funds from a Byron wallet to a new-style wallet.

# Usage

The basic sequence of a complete migration would be:

1. Use [`postByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/774) to restore a Byron wallet.
1. Use [`postWallet`](https://github.com/input-output-hk/cardano-wallet/blob/918ebab28d27ed89c6cd0f0b84a53794180ea121/specifications/api/swagger.yaml#L850) to create a new-style wallet (if one does not already exist). 
1. Use [`migrateByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/779) to migrate funds from the Byron wallet to the new-style wallet.
1. Use [`deleteByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/777) to delete the now-empty Byron wallet.

# Decision

The API will provide an endpoint similar to the following:
```yaml
/byron/wallets/{byronWalletId}/migrate/{walletId}:
  post:
    operationId: migrateByronWallet
    tags: ["Wallets"]   
    summary: Migrate  
    description: |
      Migrate all funds from a Byron wallet to a new-style wallet.
    parameters:
      - *parametersByronWalletId
      - *parametersWalletId
      - <<: *parametersBody 
        schema: *ApiMigrateByronWalletData 
    responses: *responsesMigrateByronWallet
```
With schema definitions similar to the following:
```yaml
ApiMigrateByronWalletData: &ApiMigrateByronWalletData 
  type: object
  required:
    - passphrase
  properties: 
    passphrase:
      <<: *walletPassphrase
      description: The wallet's master passphrase.
```

# Acceptance Criteria

Within the list of criteria below, a _**ticked**_ criterion indicates that there is _**test coverage**_ in the `master` branch to demonstrate that this criterion is _**satisfied**_.

- [x] The API _must_ provide a simple operation to migrate funds from a Byron wallet to a new-style wallet (the `migrateByronWallet` operation).
- [x] If the user erroneously specifies a _Shelly_ wallet ID as the _source_ wallet when calling `migrateByronWallet`, the operation _must_ fail with an error. The error _should_ include a user-friendly explanation informing them that they have specified the _wrong type_ of wallet as a _source_ wallet.
- [x] If the user erroneously specifies a _Byron_ wallet ID as the _target_ wallet when calling `migrateByronWallet`, the operation _must_ fail with an error. The error _should_ include a user-friendly explanation informing them that they have specified the _wrong type_ of wallet as a _target_ wallet.
- [x] The actual cost incurred by the migration _must_ exactly match the cost returned by the [`getByronWalletMigrateInfo`](https://github.com/input-output-hk/cardano-wallet/issues/778) endpoint. Therefore, the balance of the new wallet must be equal to `b - c`, where `b` was the original balance of the legacy wallet, and `c` is the cost returned by [`getByronWalletMigrateInfo`](https://github.com/input-output-hk/cardano-wallet/issues/778).
- [x] After a successful migration, data relating to the original wallet _should_ still be present in the database.
- [x] After a successful migration, calling [`getByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/776) with the migrated wallet ID _should_ still succeed.
- [x] After a successful migration, calling [`getByronWallet`](https://github.com/input-output-hk/cardano-wallet/issues/776) with the migrated wallet ID _must_ report a balance of `0`.
- [x] After a successful migration, the [`listByronWallets`](https://github.com/input-output-hk/cardano-wallet/issues/775) operation _should_ still include the migrated wallet in the list it returns.

# PR

| Number | Base |
| -- | -- |
| #795 | master |
| #806 | master |
| #871 | master |
| #890 | master |
| #950 | master |

# QA

- [x] Build integration tests to verify that all acceptance criteria have been satisfied.

**Comment by piotr-iohk** [comment]
I have reviewed integration tests, they are quite nice. 

I would like to add few more mostly around negative cases (BYRON_MIGRATE and BYRON_CALCULATE in the file): https://docs.google.com/spreadsheets/d/1fadIA_j4nCd3FbylPo5J8K9Fy6tixSC2T9V3xHKuUvU/edit#gid=0
I don't see many tests for caluclating migration cost too. (they are touched in the BYRON_MIGRATE suite)

Also testing of of big wallet with many transactions and fragmented utxo from genesis file would be beneficial.

Also response codes might be not complete for byron migrate (https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/migrateByronWallet) I think `415` might be missing.

**Comment by jonathanknowles** [comment]
@piotr-iohk wrote:
> I don't see many tests for calculating migration cost too. 

Good point. It's true that we don't have many tests to trigger a migration cost calculation in the integration layer.

Though have you seen the [property tests for migration coin selection](https://github.com/input-output-hk/cardano-wallet/blob/b46df2f29baf347c3a7d42ea8f071547cc28b3ed/lib/core/test/unit/Cardano/Wallet/Primitive/CoinSelection/MigrationSpec.hs)?

The `GetByronWalletMigrationInfo` endpoint is basically a wrapper around the `selectCoinsForMigration` function.

Can you see any deficiencies in the set of property tests above? If so, perhaps we can flesh them out a bit more.

**Comment by piotr-iohk** [comment]
@jonathanknowles I think property tests look good. I have added a few more integration tests in #989.

**Comment by piotr-iohk** [comment]
I have added yet additional tests in #1008 and an issue #1007 that actually was inspired by this comment https://github.com/input-output-hk/cardano-wallet/pull/989#discussion_r344434182.

Closing this one.
